platform :ios, '11.4'
use_frameworks!

target 'inngage-objectivec-sample' do
  pod 'Inngage/Core', :path => '../../'
end

def extension_pods 
  pod 'Inngage/NotificationExtension', :path => '../../'
end

target 'NotificationServiceExtension' do
  extension_pods
end

target 'NotificationUIExtension' do
  extension_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end